# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_recipe_url_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='url_path',
            new_name='from_url',
        ),
    ]
