# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-01 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20180325_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
